version: "3"
#==========================VOLUMES==========================
volumes:
  pgdata:

#==========================SERVICES==========================
services:
  #-----------------------popmodeler-----------------------
  popmodeler:
    image: registry.gitlab.com/popmodeler/backend/laravel
    container_name: popmodeler
    ports:
      - 80:80
    environment:
      APACHE_RUN_USER: "#1001"
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    volumes:
      - ./:/var/www/html
    restart: always

  #----------------------------PGSQL--------------------------

  db:
    image: postgres:12
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: popmodeler
    volumes:
      - pgdata:/var/lib/postgresql/data
